# Generated by Django 5.1.7 on 2025-05-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_post_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photos",
            field=models.ImageField(blank=True, null=True, upload_to="uploaded_image/"),
        ),
    ]
