# Generated by Django 5.1.7 on 2025-05-30 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0011_follow_followed_alter_follow_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="followed",
        ),
    ]
